name: Reusable Workflow 
on:
  workflow_call:
    inputs:
      env-name:
        required: true
        type: string
    
    secrets:
      env-secret: #this vare will get the value of the secret that we want to use in the reusable workflow
        required: true
jobs:
  deploy:
    name: Deploy to ${{ inputs.env-name }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.env-name }}

    steps:
      - name: 🚀 Simular Despliegue
        run: |
          echo "Conectando a Google Cloud para el entorno: ${{ inputs.env-name }}"
          echo "Mensaje del entorno: ${{ secrets.env-secret }}"
          echo "Status: Despliegue completado con éxito."